# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scalica.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='scalica.proto',
  package='processor',
  syntax='proto2',
  serialized_pb=_b('\n\rscalica.proto\x12\tprocessor\"D\n\x12ProcessPostRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x0f\n\x07post_id\x18\x02 \x01(\x03\x12\x0c\n\x04text\x18\x03 \x01(\t\"\"\n\x10ProcessPostReply\x12\x0e\n\x06\x64igest\x18\x01 \x01(\t2X\n\tProcessor\x12K\n\x0bProcessPost\x12\x1d.processor.ProcessPostRequest\x1a\x1b.processor.ProcessPostReply\"\x00\x42\"\n net.yairsovran.scalica.processor')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PROCESSPOSTREQUEST = _descriptor.Descriptor(
  name='ProcessPostRequest',
  full_name='processor.ProcessPostRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='processor.ProcessPostRequest.user_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='post_id', full_name='processor.ProcessPostRequest.post_id', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='processor.ProcessPostRequest.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=96,
)


_PROCESSPOSTREPLY = _descriptor.Descriptor(
  name='ProcessPostReply',
  full_name='processor.ProcessPostReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='digest', full_name='processor.ProcessPostReply.digest', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['ProcessPostRequest'] = _PROCESSPOSTREQUEST
DESCRIPTOR.message_types_by_name['ProcessPostReply'] = _PROCESSPOSTREPLY

ProcessPostRequest = _reflection.GeneratedProtocolMessageType('ProcessPostRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSPOSTREQUEST,
  __module__ = 'scalica_pb2'
  # @@protoc_insertion_point(class_scope:processor.ProcessPostRequest)
  ))
_sym_db.RegisterMessage(ProcessPostRequest)

ProcessPostReply = _reflection.GeneratedProtocolMessageType('ProcessPostReply', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSPOSTREPLY,
  __module__ = 'scalica_pb2'
  # @@protoc_insertion_point(class_scope:processor.ProcessPostReply)
  ))
_sym_db.RegisterMessage(ProcessPostReply)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n net.yairsovran.scalica.processor'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class ProcessorStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ProcessPost = channel.unary_unary(
        '/processor.Processor/ProcessPost',
        request_serializer=ProcessPostRequest.SerializeToString,
        response_deserializer=ProcessPostReply.FromString,
        )


class ProcessorServicer(object):

  def ProcessPost(self, request, context):
    """Do something with a newly-received Post from a user.
    For now, just returns the SHA256 digest of the post's text.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProcessorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ProcessPost': grpc.unary_unary_rpc_method_handler(
          servicer.ProcessPost,
          request_deserializer=ProcessPostRequest.FromString,
          response_serializer=ProcessPostReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'processor.Processor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaProcessorServicer(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def ProcessPost(self, request, context):
    """Do something with a newly-received Post from a user.
    For now, just returns the SHA256 digest of the post's text.
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaProcessorStub(object):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This class was generated
  only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
  def ProcessPost(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Do something with a newly-received Post from a user.
    For now, just returns the SHA256 digest of the post's text.
    """
    raise NotImplementedError()
  ProcessPost.future = None


def beta_create_Processor_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_deserializers = {
    ('processor.Processor', 'ProcessPost'): ProcessPostRequest.FromString,
  }
  response_serializers = {
    ('processor.Processor', 'ProcessPost'): ProcessPostReply.SerializeToString,
  }
  method_implementations = {
    ('processor.Processor', 'ProcessPost'): face_utilities.unary_unary_inline(servicer.ProcessPost),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_Processor_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  """The Beta API is deprecated for 0.15.0 and later.

  It is recommended to use the GA API (classes and functions in this
  file not marked beta) for all further purposes. This function was
  generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
  request_serializers = {
    ('processor.Processor', 'ProcessPost'): ProcessPostRequest.SerializeToString,
  }
  response_deserializers = {
    ('processor.Processor', 'ProcessPost'): ProcessPostReply.FromString,
  }
  cardinalities = {
    'ProcessPost': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'processor.Processor', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
